const MentorAccountDetails=[
    {id:1,
        mentorName:"Om Sovan Das ",
        mentorEmail:"omsovandas@gmail.com",
        AccountDetail:{
            accountHolderName:"Om Sovan Das",
            accountType:"Savings Account",
            accountNumber:"35159966279",
            bankName:"State Bank of India",
            bankAdress:"IRC Village, Bhubaneswar",
            ifscCode:"SBIN0007045",
            upiId:"",
        }
    },
    {id:2,
        mentorName:" Heena Mansuri",
        mentorEmail:"96heenamansuri@gmail.com",
        AccountDetail:{
            accountHolderName:"HEENA MOHAMMED AFZAL MANSURI",
            accountType:"SAVING",
            accountNumber:"50100224814558",
            bankName:"HDFC Bank",
            bankAdress:"NARIMAN PT - EXPRESS TOWERS",
            ifscCode:"HDFC0000291",
            upiId:"8610387916@hdfcbank",
        }
    },
    {id:3,
        mentorName:"Shathyan Raja",
        mentorEmail:"shathyanr@gmail.com",
        AccountDetail:{
            accountHolderName:"",
            accountType:"",
            accountNumber:"",
            bankName:"",
            bankAdress:"",
            ifscCode:"",
            upiId:"shathyanr@okicici",
        }
    },
    {id:4,
        mentorName:"Utkarsh Sardesai",
        mentorEmail:"usutkarshsardesai20@gmail.com",
        AccountDetail:{
            accountHolderName:"",
            accountType:"",
            accountNumber:"",
            bankName:"",
            bankAdress:"",
            ifscCode:"",
            upiId:"7972720692@ybl",
        }
    },
    {id:5,
        mentorName:"Kishita Thakar",
        mentorEmail:"askkareerkite@gmail.com",
        AccountDetail:{
            accountHolderName:"Kishita Thakar",
            accountType:"Savings",
            accountNumber:"913010055525794",
            bankName:"Axis Bank",
            bankAdress:"Plot No 1, Beaumonde CHS, Swami Vivekananda Rd, Malad, Sunder Nagar, Mumbai, Maharashtra 400064",
            ifscCode:"UTIB0001347",
            upiId:"kishitathakar@okaxis",
        }
    },
    {id:6,
        mentorName:"Navnita Pattnaik",
        mentorEmail:"msmeforum.info@gmail.com",
        AccountDetail:{
            accountHolderName:"Navnita Pattnaik",
            accountType:"Savings",
            accountNumber:"10091794570",
            bankName:"State Bank of India",
            bankAdress:"Rajpath,75, Bhubaneswar",
            ifscCode:"SBIN0007188",
            upiId:"",
        }
    },
    {id:7,
        mentorName:"Mohit kadayan",
        mentorEmail:"mohitk1820@gmail.com",
        AccountDetail:{
            accountHolderName:"",
            accountType:"",
            accountNumber:"",
            bankName:"",
            bankAdress:"",
            ifscCode:"",
            upiId:"mohitkadayan@ybl",
        }
    },
    {id:8,
        mentorName:"Niranjan Ingale",
        mentorEmail:"niranjan@profound-data.com",
        AccountDetail:{
            accountHolderName:"Niranjan Ingale",
            accountType:"Saving Account",
            accountNumber:"910010035343032",
            bankName:"United Trust International Bank",
            bankAdress:"Main Branch, Pune",
            ifscCode:"UTIB0000037",
            upiId:"",
        }
    },
    {id:9,
        mentorName:"Prof.Anubhav Singh",
        mentorEmail:"singhanubhav05@gmail.com",
        AccountDetail:{
            accountHolderName:"",
            accountType:"",
            accountNumber:"",
            bankName:"",
            bankAdress:"",
            ifscCode:"",
            upiId:"switch2anu1@ybl",
        }
    },
   
    {id:11,
        mentorName:"Rishav Agarwal",
        mentorEmail:"rishav@picxele.com",
        AccountDetail:{
            accountHolderName:"Rishav Agarwal",
            accountType:"Savings",
            accountNumber:"34672140871",
            bankName:"SBI",
            bankAdress:"Asansol",
            ifscCode:"SBIN0000011",
            upiId:"8759456371@paytm",
        }
    },
   
    {id:13,
        mentorName:"Vishakha Verma",
        mentorEmail:"vishakhaverma185@gmail.com",
        AccountDetail:{
            accountHolderName:"Vishakha Verma",
            accountType:"Current",
            accountNumber:"50100154494480",
            bankName:"HDFC Bank",
            bankAdress:"Marathahalli Junction",
            ifscCode:"HDFC0003636",
            upiId:"",
        }
    },
    {id:14,
        mentorName:"Rohit Gupta",
        mentorEmail:"rgupta.success@gmail.com",
        AccountDetail:{
            accountHolderName:"Rohit Gupta",
            accountType:"Savings",
            accountNumber:"912010019670123",
            bankName:"Axis Bank",
            bankAdress:"GROUND FLOOR, BLOCK K-20, GREEN CITY, E-8, GULMOHAR COLONY, BHOPAL (MP) - 462039",
            ifscCode:"UTIB0001682",
            upiId:"rgupta.success@okhdfcbank",
        }
    },
    {id:15,
        mentorName:"Ishwar R Jivani",
        mentorEmail:"irjivani87@gmail.com",
        AccountDetail:{
            accountHolderName:"Shital Ishwarbhai Jivani",
            accountType:"Current Account",
            accountNumber:"239705500601",
            bankName:"ICICI Bank",
            bankAdress:"BHAGAL, Surat",
            ifscCode:"ICIC0002397",
            upiId:"",
        }
    },
    {id:16,
        mentorName:"Girish Ayya",
        mentorEmail:"girish@avadhauto.com",
        AccountDetail:{
            accountHolderName:"GIRISH N AYYA",
            accountType:"",
            accountNumber:"04461530001617",
            bankName:"HDFC Bank",
            bankAdress:"GandhiBazar Main Road , Bangalore – 560 004",
            ifscCode:"HDFC0000446",
            upiId:"",
        }
    },
    {id:17,
        mentorName:"Sudhanshu Srivastava",
        mentorEmail:"Darpan6123@live.com",
        AccountDetail:{
            accountHolderName:"",
            accountType:"",
            accountNumber:"",
            bankName:"",
            bankAdress:"",
            ifscCode:"",
            upiId:"8130873387@upi",
        }
    },
    
    {id:19,
        mentorName:"Parijat Chandra Pathak",
        mentorEmail:"parijat.pathak@gmail.com",
        AccountDetail:{
            accountHolderName:"Parijat Chandra Pathak",
            accountType:"Savings",
            accountNumber:"1411309799",
            bankName:"Kotak Mahindra Bank",
            bankAdress:"Zone I MP Nagar , Bhopal",
            ifscCode:"KKBK0000753",
            upiId:"",
        }
    },
    {id:20,
        mentorName:"Venkat Balantrapu",
        mentorEmail:"vbalantrapu@yahoo.com",
        AccountDetail:{
            accountHolderName:"Quality Service Awareness Institute",
            accountType:"Current",
            accountNumber:"62483428659",
            bankName:"State Bank Of India",
            bankAdress:"Sholinganallur Branch, Chennai",
            ifscCode:"SBIN0021226",
            upiId:"",
        }
    },
    
    {id:22,
        mentorName:"Nitish Toppo",
        mentorEmail:"nitishtoppo316@gmail.com",
        AccountDetail:{
            accountHolderName:"Nitish Toppo",
            accountType:"Savings",
            accountNumber:"20465472840",
            bankName:"State Bank of India",
            bankAdress:"Birpara",
            ifscCode:"SBIN0002025",
            upiId:"",
        }
    },
    {id:23,
        mentorName:"Dr Saurabh Bhatia",
        mentorEmail:"s.bhatia@tsmls.org",
        AccountDetail:{
            accountHolderName:" Saurabh Bhatia",
            accountType:"Savings",
            accountNumber:"000501540604",
            bankName:"ICICI Bank",
            bankAdress:" bund garden pune branch",
            ifscCode:"ICIC0000005",
            upiId:"Saurabhbhatia007-1@okicici",
        }
    },
    {id:24,
        mentorName:"Dr Girish Sapra",
        mentorEmail:"girish.sapra1@gmail.com",
        AccountDetail:{
            accountHolderName:"GIRISH SAPRA",
            accountType:"Savings",
            accountNumber:"65178785979",
            bankName:"State Bank of India",
            bankAdress:"NITJ",
            ifscCode:"SBIN0050841",
            upiId:"girish.sapra1@okssbi",
        }
    },
    {id:25,
        mentorName:"Sujit S Nair",
        mentorEmail:"sn@nairsujit.com",
        AccountDetail:{
            accountHolderName:"Sujitkumar Somakumaran Nair",
            accountType:"Savings",
            accountNumber:"910010037736140",
            bankName:"Axis Bank Ltd",
            bankAdress:"CORPORATE CENTER, ANDHERI-EAST",
            ifscCode:"UTIB0000328",
            upiId:"",
        }
    },
    {id:26,
        mentorName:"Rohan Karnataki",
        mentorEmail:"rohankarnataki@gmail.com",
        AccountDetail:{
            accountHolderName:"",
            accountType:"",
            accountNumber:"",
            bankName:"",
            bankAdress:"",
            ifscCode:"",
            upiId:"rohankarnataki@okaxis",
        }
    },
   
    {id:29,
        mentorName:"Jaideep Pyne",
        mentorEmail:"jaideeppyne1997@gmail.com",
        AccountDetail:{
            accountHolderName:"Jaideep Pyne",
            accountType:"Savings",
            accountNumber:"920010061230927",
            bankName:"Axis Bank",
            bankAdress:"Axis Bank, Behala Manton branch",
            ifscCode:"UTIB0000721",
            upiId:"jaideeppyne1997@ybl",
        }
    },
    {id:30,
        mentorName:"Viraj Patil",
        mentorEmail:"patvraj@gmail.com",
        AccountDetail:{
            accountHolderName:"VIRAJ RAVINDRA PATIL",
            accountType:"Savings",
            accountNumber:"01651000106235",
            bankName:"HDFC Bank",
            bankAdress:"Karad, Near Hotel Sangam on Pune Bangalore Highway, 415110, Dist: Satara Maharashtra,",
            ifscCode:"HDFC0000165",
            upiId:"9637252378@ybl",
        }
    },
    {id:31,
        mentorName:"Mahesh Shivanna",
        mentorEmail:"shivannamahesh@gmail.com",
        AccountDetail:{
            accountHolderName:"",
            accountType:"",
            accountNumber:"",
            bankName:"",
            bankAdress:"",
            ifscCode:"",
            upiId:"9739554488@ybl",
        }
    },
    {id:32,
        mentorName:"Punita Parekh",
        mentorEmail:"parekh.punita@gmail.com",
        AccountDetail:{
            accountHolderName:"PUNITA PAREKH",
            accountType:"Savings",
            accountNumber:"0060114016310",
            bankName:"HDFC Bank",
            bankAdress:"Fort Mumbai",
            ifscCode:"HDFC0000060",
            upiId:"",
        }
    },
   
    {id:34,
        mentorName:"Vishesh Chopra",
        mentorEmail:"vcsa123@gmail.com",
        AccountDetail:{
            accountHolderName:"",
            accountType:"",
            accountNumber:"",
            bankName:"",
            bankAdress:"",
            ifscCode:"",
            upiId:"vishesh.chopra123@okhdfcbank",
        }
    },
    
    {id:36,
        mentorName:"Aman Khajanchi",
        mentorEmail:"khajanchi.aman@gmail.com",
        AccountDetail:{
            accountHolderName:"Aman Sundarlal Khajanchi",
            accountType:"Savings",
            accountNumber:" 00091610002612",
            bankName:"HDFC Bank Limited",
            bankAdress:"Kasturba Road Branch, Bangalore",
            ifscCode:" HDFC0000009",
            upiId:"",
        }
    },
    {id:37,
        mentorName:"Manoj Kumar Jena",
        mentorEmail:"manojkjena@knktindia.com",
        AccountDetail:{
            accountHolderName:"Adhar Kumar Jena & Manoj Kumar Jena",
            accountType:"Savings",
            accountNumber:"30480228388",
            bankName:"State Bank of India",
            bankAdress:"Shyam Nagar, Kanpur, Uttar Pradesh",
            ifscCode:"SBIN0000108",
            upiId:"",
        }
    },
   
    {id:39,
        mentorName:"Preeti Chothani",
        mentorEmail:"preetichothani@sdlawconsultancy.com",
        AccountDetail:{
            accountHolderName:"Shree Datta Law Consultancy",
            accountType:"Current",
            accountNumber:"40935424431",
            bankName:"State Bank of India",
            bankAdress:"Suman tower, Gandhinagar",
            ifscCode:"SBIN0032214",
            upiId:"chothani18preeti@oksbi",
        }
    },
    
    {id:40,
        mentorName:"Devish Raj",
        mentorEmail:"devish2@mealobox.in",
        AccountDetail:{
            accountHolderName:"Devesh Raj",
            accountType:"Savings",
            accountNumber:"20219953424",
            bankName:"State Bank of India",
            bankAdress:"ADB Hardoi",
            ifscCode:"SBIN0005304",
            upiId:"",
        }
    },
    
    
    {id:43,
        mentorName:"Nikhil Shinde ",
        mentorEmail:"nikhil2617.shinde@gmail.com",
        AccountDetail:{
            accountHolderName:"Nikhil Ramesh Shinde",
            accountType:"Savings",
            accountNumber:"697701606248",
            bankName:"ICICI Bank",
            bankAdress:"Andheri Kurla Road",
            ifscCode:"ICIC0006977",
            upiId:"nikk2617@ybl",
        }
    },
   
    
    {id:48,
        mentorName:"Kumar Raja Masanam",
        mentorEmail:"1mail2kumarraja@gmail.com",
        AccountDetail:{
            accountHolderName:"M SRI KUMAR RAJA",
            accountType:"Savings",
            accountNumber:"918010028367728",
            bankName:"United Trust International Bank",
            bankAdress:"Hyderabad",
            ifscCode:"UTIB0000008",
            upiId:"",
        }
    },
    {id:35,
        mentorName:"Megha Bhansali",
        mentorEmail:"megha@hjmbandassociates.com",
        AccountDetail:{
            accountHolderName:" Megha Bhansali",
            accountType:"Savings",
            accountNumber:"50100100894982",
            bankName:"HDFC Bank ",
            bankAdress:"Gopalpura Tonk Road, Jaipur",
            ifscCode:"HDFC0003849",
            upiId:"",
        }
    },
    {id:49,
        mentorName:"Yash Barot",
        mentorEmail:"",
        AccountDetail:{
            accountHolderName:"",
            accountType:"",
            accountNumber:"",
            bankName:"",
            bankAdress:"",
            ifscCode:"",
            upiId:"",
        }
    },
    {id:50,
        mentorName:"Vaibhav Goyal",
        mentorEmail:"vaibhav@digitaloutcomes.io",
        AccountDetail:{
            accountHolderName:"",
            accountType:"",
            accountNumber:"",
            bankName:"",
            bankAdress:"",
            ifscCode:"",
            upiId:"",
        }
    },
    {id:41,
        mentorName:"Malak",
        mentorEmail:"malak@smartgain.org",
        AccountDetail:{
            accountHolderName:"",
            accountType:"",
            accountNumber:"",
            bankName:"",
            bankAdress:"",
            ifscCode:"",
            upiId:"",
        }
    },
    {id:47,
        mentorName:"Subhajit Bhattacharya",
        mentorEmail:"subhajit.bhattacharya07@gmail.com",
        AccountDetail:{
            accountHolderName:"",
            accountType:"",
            accountNumber:"",
            bankName:"",
            bankAdress:"",
            ifscCode:"",
            upiId:"",
        }
    },
    {id:46,
        mentorName:"Nipun Grover",
        mentorEmail:"nipun@accountsnest.com",
        AccountDetail:{
            accountHolderName:"",
            accountType:"",
            accountNumber:"",
            bankName:"",
            bankAdress:"",
            ifscCode:"",
            upiId:"",
        }
    },
    {id:45,
        mentorName:"Harish Gadagin",
        mentorEmail:"gadaginharish@gmail.com",
        AccountDetail:{
            accountHolderName:"",
            accountType:"",
            accountNumber:"",
            bankName:"",
            bankAdress:"",
            ifscCode:"",
            upiId:"",
        }
    },
    {id:44,
        mentorName:"Abani Jha",
        mentorEmail:"abanijha@gmail.com",
        AccountDetail:{
            accountHolderName:"",
            accountType:"",
            accountNumber:"",
            bankName:"",
            bankAdress:"",
            ifscCode:"",
            upiId:"",
        }
    },
    {id:42,
        mentorName:"Jayanta Mohanty",
        mentorEmail:"jayanta.k.mohanty1@gmail.com",
        AccountDetail:{
            accountHolderName:"",
            accountType:"",
            accountNumber:"",
            bankName:"",
            bankAdress:"",
            ifscCode:"",
            upiId:"",
        }
    },
    {id:38,
        mentorName:"Nitish Garg ",
        mentorEmail:"",
        AccountDetail:{
            accountHolderName:"",
            accountType:"",
            accountNumber:"",
            bankName:"",
            bankAdress:"",
            ifscCode:"",
            upiId:"",
        }
    },
    {id:33,
        mentorName:"Mayur Achari",
        mentorEmail:"mayurachari@gmail.com",
        AccountDetail:{
            accountHolderName:"",
            accountType:"",
            accountNumber:"",
            bankName:"",
            bankAdress:"",
            ifscCode:"",
            upiId:"",
        }
    },
    {id:28,
        mentorName:"Shudhanshu Mishra",
        mentorEmail:"me.shudhanshumishra@gmail.com",
        AccountDetail:{
            accountHolderName:"",
            accountType:"",
            accountNumber:"",
            bankName:"",
            bankAdress:"",
            ifscCode:"",
            upiId:"",
        }
    },
   
    {id:10,
        mentorName:"Vikas Agarwal",
        mentorEmail:"vikas@purply.in",
        AccountDetail:{
            accountHolderName:"",
            accountType:"",
            accountNumber:"",
            bankName:"",
            bankAdress:"",
            ifscCode:"",
            upiId:"",
        }
    },
    {id:12,
        mentorName:"Arjit Singh",
        mentorEmail:"arjitsingh1171@gmail.com",
        AccountDetail:{
            accountHolderName:"",
            accountType:"",
            accountNumber:"",
            bankName:"",
            bankAdress:"",
            ifscCode:"",
            upiId:"",
        }
    },
    {id:18,
        mentorName:"Kushal Trivedi",
        mentorEmail:"kushtrivedi26@gmail.com",
        AccountDetail:{
            accountHolderName:"",
            accountType:"",
            accountNumber:"",
            bankName:"",
            bankAdress:"",
            ifscCode:"",
            upiId:"",
        }
    },
    {id:21,
        mentorName:"Ranjith Rao",
        mentorEmail:"ranjith@ervaring.in",
        AccountDetail:{
            accountHolderName:"",
            accountType:"",
            accountNumber:"",
            bankName:"",
            bankAdress:"",
            ifscCode:"",
            upiId:"",
        }
    },
    {id:27,
        mentorName:"Nitin Sharma",
        mentorEmail:"nitinsharma11@gmail.com",
        AccountDetail:{
            accountHolderName:"",
            accountType:"",
            accountNumber:"",
            bankName:"",
            bankAdress:"",
            ifscCode:"",
            upiId:"",
        }
    },
]

export default MentorAccountDetails