export const courseDataBusinessPlanning = {
  frontscreen: {
    images: [
      'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%2C%20analytics%2C%20sucess%2C%20startup%2C%20Technology%20_%20account%2C%20setting%2C%20options%2C%20preferences.png?alt=media&token=d017d4cc-0626-488c-8b25-2a478282e65b',
      'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FFinances.png?alt=media&token=33a14e0c-7a36-4212-add7-bc57254b2aa9',
    ],
    name: 'BUSINESS PLANNING',
  },
  modules: [
   {
    name:"model1",
    slides:[
    {
      heading: 'What is Business Planning?',
      image:'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FFinances.png?alt=media&token=33a14e0c-7a36-4212-add7-bc57254b2aa9',
      type: 'intro',
    },
    {
      text: "“An idea without a plan is just an idea”",
      image:'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FFinances.png?alt=media&token=33a14e0c-7a36-4212-add7-bc57254b2aa9',
      type: 'textimg',
    },
    {
      text: "You might have already heard about the importance of a well-constructed business plan.\n\nBut you might not know what exactly a business plan is, what are its key elements, what things you should include and make a clear, well-written plan that can attract people towards your business and get them involved. We are here to help.",
      image:'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'textimg',
    },
    {
      text: "We are here to help.",
      image:'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%2C%20analytics%2C%20sucess%2C%20startup%2C%20Technology%20_%20account%2C%20setting%2C%20options%2C%20preferences.png?alt=media&token=d017d4cc-0626-488c-8b25-2a478282e65b',
      type: 'textimg',
    },
    {
      heading: 'What is actually a business plan?',
      image:'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FFinances.png?alt=media&token=33a14e0c-7a36-4212-add7-bc57254b2aa9',
      type: 'intro',
    },
    {
      text: "Business Plan is a document that helps Investors and readers understand your business goals and the steps you’re taking to reach them.",
      image:'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'textimg',
    },
    {
      text: "An “actionable plan” requires a bit of work. The best business plans are not just informative; they also excite and persuade readers about taking part (and benefiting from it) in helping your business succeed.",
      image:'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'textimg',
    },
    {
      text: "How do you do this?",
      image:'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'textimg',
    },
    {
      text: "You do this by answering the major, fundamental questions that your readers will have about your business going forward.\n\nThese questions fall into two key categories: the WHY questions and the HOW questions.",
      image:'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'textimg',
    },
    {
      question: 'What is business planning?',
      options: [
        'Business Plan is a document that helps employees understand your business goals and the steps you’re taking to reach them.',
        'Business Plan is a document that helps you understand your business goals and the steps you’re taking to reach them.',
        'Business Plan is a document that helps Investors and readers understand your business goals and the steps you’re taking to reach them.',
        'Business Plan is a document that helps Investors and readers understand your business model you’re taking to reach them.',
      ],
      ans: 2,
      type: 'quiz',
    },
    {
      text: "The WHY Questions:\n\n- Why this?\n- Why now?\n- Why you?",
      image:'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'textimg',
    },
    {
      text: "The HOW Questions:\n\n- How will you make money?\n- How will you get customers?\n- How will you grow your business?",
      image:'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'textimg',
    },
    {
      text: "And while answering these questions your business plan should also highlight how your company has the right product and the right market.",
      image:'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'textimg',
    },
    {
      heading: 'Why do you need a business plan?',
      text: "",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: '1. To Develop your strategies',
      text: "Writing down your goals and analyzing market helps you discover new trends in the industry that could help you develop your strategies.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: '2. To guide you',
      text: "A business plan gives you direction and helps you sort out your ideas, so you can set your goals, prioritize them and create a strategy to reach them.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: '3. To attract Investors',
      text: "A potential investor wants proof that their time and money will be repaid when they invest in your business. Your business plan helps you make that case.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      question: 'Which of the following is NOT one of the reason you need business plan',
      options: [
        'To guide you',
        'To develop strategies',
        'To attract customers',
        'To form strategic partnerships',
      ],
      ans: 3,
      type: 'quiz',
    },
    {
      heading: 'Who Needs a Business Plan?',
      image:'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FFinances.png?alt=media&token=33a14e0c-7a36-4212-add7-bc57254b2aa9',
      type: 'intro',
    },
    {
      heading: '1. Business Seeking funding',
      text: "If you aim to raise money to support or grow your business. Having a business plan is a necessity. Having a business plan increases the likelihood of obtaining funding.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: '2. Established Companies Managing Their Businesses',
      text: "Unlike startups, existing businesses make extensive use of business plans with a view to directing business and accelerating and tracking growth. Established businesses also use business plans to convince consumers to find a company or bring potential partners or employees to the herd.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: 'How to choose a good Business Plan',
      text: "Depending on your stage of growth and what you intend to use, business plans can come in a number of different forms.\n\nLet's take a quick look at a few of the most common examples.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: '1. General Business Plan',
      text: "If your goal is to convince investors to financially support your business, a general business plan - or \"external business plan\", as it is sometimes called - is the most frequently requested response you will need.\n\nGeneral business plans are very well set up and focus on showing investors how your vision translates into greater profits compared to the domestic business.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: '2. One-Page Business Plan',
      text: "A one-page business plan is actually an executive summary - in other words, the TL; DR version of your business plan where you break down every major part of your business plan into a phase or two, giving investors the opportunity to step in. - see key points.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      text: "One pager is a great help to create early conversations with a potential investor. Investors are incredibly busy, so one pager is a great way to go when you are trying to arouse interest and set up a forum for in-depth discussions about your business after your initial contact.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'textimg',
    },
    {
      heading: '3. Internal Business Plan',
      text: "As its name implies, internal business plans often reside within the office and are designed to serve as a management tool to help business owners plan and meet goals.\n\nInternal business plans are less concerned with covering issues such as overall team vision or problem solving and are more focused on business strategies, which is the next milestone, budget, and forecast. This type of business plan is more commonly used by companies that are more established than startups.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      question: 'Which of the following best describes a one-pager business plan?',
      options: [
        'plans are very well set up and focus on showing investors how your vision translates into greater profits compared to the domestic business.',
        'plans often reside within the office and are designed to serve as a management tool to help business owners plan and meet goals.',
        'is a great way to go when you are trying to arouse interest and set up a forum for in-depth discussions about your business after your initial contact',
        'Both A and c',
      ],
      ans: 1,
      type: 'quiz',
    },
    ]
   },
   {
    name:"model2",
    slides:[
    {
      heading: 'Key Components of a Business Plan',
      image:'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FFinances.png?alt=media&token=33a14e0c-7a36-4212-add7-bc57254b2aa9',
      type: 'intro',
    },
    {
      heading: 'A. Executive Summary',
      text: "Your Executive Summary is a brief overview of your overall business plan. The goal is to break down each keyword into a sentence or two in order to convey the vision of your business and prepare the reader for future content.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: 'B. Company Description',
      text: "The Company Profile will serve as a “great vision statement” that introduces your company, what it does, and why it is important. It conveys to your readers the direction your company is going, and the scope of the business you are building.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: 'C. Problem',
      text: "Every good product or service starts with a clear and straightforward problem that you are determined to solve. What problems do your customers face that your product / service solves?\n\nIf you do not identify the problem that you are solving properly, then the solution (and your entire system) will fall into disrepair.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: 'D. Solution',
      text: "Once you have identified a problem that you intend to solve, highlight how your product / service connects right back to that problem and resolve it effectively.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%2C%20analytics%2C%20sucess%2C%20startup%2C%20Technology%20_%20account%2C%20setting%2C%20options%2C%20preferences.png?alt=media&token=d017d4cc-0626-488c-8b25-2a478282e65b',
      type: 'headtextimg',
    },
    {
      heading: 'E. Market Size',
      text: "\n- What is the size of your addressable market?\n- Is it growing? How much?\n- Is the market big enough for potential investors to enjoy?\n- Has there been a significant exit from similar companies in your space?",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%2C%20analytics%2C%20sucess%2C%20startup%2C%20Technology%20_%20account%2C%20setting%2C%20options%2C%20preferences.png?alt=media&token=d017d4cc-0626-488c-8b25-2a478282e65b',
      type: 'headtextimg',
    },
    {
      question: 'What statement best describes the key component “Company description”',
      options: [
        'you don’t know how to properly allocate contributions in capital.',
        'you know how to properly allocate contributions in capital.',
        'Both are corrYou have to split the equity equally',
        'NONe of these',
      ],
      ans: 0,
      type: 'quiz',
    },
    {
      heading: 'F. Product (How It Works)',
      text: "Provide readers with an overview of your company's products and services, their key features, with special emphasis on what makes them different from the solutions available in the market.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%2C%20analytics%2C%20sucess%2C%20startup%2C%20Technology%20_%20account%2C%20setting%2C%20options%2C%20preferences.png?alt=media&token=d017d4cc-0626-488c-8b25-2a478282e65b',
      type: 'headtextimg',
    },
    {
      heading: 'G. Revenue Model',
      text: "\n- How does your company (or will) make money?\n- How do you set prices for your product / service?\n- How does your price compare to similar products on the market?\n- How much is your revenue projection for the next 5 years?",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: 'H. Operating Model',
      text: "While your Revenue Model outlines how you will make money, your Operating Model is all about smart ways to manage costs and work efficiently to earn it.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: 'I. Competitive Analysis',
      text: "\n- Identify other similar companies operating in your same area:\n- What is your strength, and how do you plan to utilize it?\n- What are their weaknesses and how do they translate into the profitability of your company?",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: 'J. Customer Description',
      text: "Describe your customer to help readers gain a clearer understanding of who might use and purchase your product:\n - What are their personas?\n - What are their Demographics?\n - What motivates them to take action (buy)?",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      question: 'Which of the following is sweat equity?',
      options: [
        'Operating Model',
        'Business Canvas Model',
        'product',
        'market',
      ],
      ans: 1,
      type: 'quiz',
    },
    {
      heading: 'K. Customer Acquisition',
      text: "\n- What strategies will you use to really get your customers involved?\n- What acquisition channels will you explore (direct marketing, paid ads, SEO, social media, etc.)?\n- What are the cost estimates for each channel?",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: 'L. Traction',
      text: "List any achievements that show readers that your company is moving:\n- Where are you in the product development process?\n- Have you established a production or manufacturing partner?\n- Have you found a significant Partner?\n- Do you have the intellectual property rights for ideas about your company?",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: 'M. Management Team',
      text: "Introduce your team and how you will work together to make the business live. The bio of each group member should include:\n- Name of group member\n- Their title and position in the company\n- Their technical background\n- Any special skills they have developed as a result of their previous experience\n- What makes them unique is driving success in your company",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: 'N. Funding',
      text: "\n- How much money do you need to complete your next milestone?\n- What are your goals (in other words, what will investors get if they exchange their investments)?\n- How will you spend your money?",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: 'O. Finance',
      text: "Decide what ideas you need to focus on to make your business successful. Common guesses include:\n- Retail price per product\n- Cost of Goods Sold\n- Customer Acquisition Costs",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      question: 'Which of the following is a part of key component “Customer acquisition”?',
      options: [
        'strategies that you will use to really get your customers involved',
        'Customer Demographics',
        'Personas of customers',
        'Both B & C',
      ],
      ans: 1,
      type: 'quiz',
    },
    {
      heading: 'How Long Should Your Business Plan Be?',
      image:'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'intro',
    },
    {
      text: "When most people think about a business plan, the first thing that usually comes to mind is an incredibly dense, 50-plus-page manifesto that’s as hard to write as it is to read.\n\nThere’s a reason why people think this. It’s because for a long time, that’s pretty much what a business plan was. Thankfully for the writer and the reader, that’s no longer the case.",
      image:'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'textimg',
    },
    {
      text: "The modern business plan as we know it today is far more concise — a mere fraction of the length of its long-winded predecessor.",
      image:'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'textimg',
    },
    {
      heading: 'A good rule of thumb is shooting for around 15 pages.',
      text: "This should give you more than enough room to provide color to each of the required sections of your business plan while also leaving some room for visual elements to break up the copy and make your business plan much more digestible (and aesthetically engaging) for readers.\n\nIf you find yourself exceeding 20 pages, there’s probably opportunities where you can go back through your plan and eliminate redundant or superfluous information.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: 'Plan On!',
      text: "In this crash course introduction to the business plan, we've thrown a lot of material at you.\n\nYou should now have a basic understanding of what a business plan is, what goes into one, and how to use one effectively.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    ]
   },
   {
    name:"model3",
    slides:[
    {
      heading: 'How to write a business Plan?',
      image:'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FFinances.png?alt=media&token=33a14e0c-7a36-4212-add7-bc57254b2aa9',
      type: 'intro',
    },
    {
      text: "Before you pick your pen and start to write we will pass through the most important things you will help you solve the process of creating yourself.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'textimg',
    },
    {
      text: "There's an old school belief that business plans must be dense, convoluted documents the size of a doorstop in order to demonstrate how serious you are about your firm.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'textimg',
    },
    {
      heading: '1. Investors short on time',
      text: "investors go through a ton of business plans a year. There is no way that an investor would dive into your 80 page long business plan and use up hours of their day going through your business plan from front to end.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%2C%20analytics%2C%20sucess%2C%20startup%2C%20Technology%20_%20account%2C%20setting%2C%20options%2C%20preferences.png?alt=media&token=d017d4cc-0626-488c-8b25-2a478282e65b',
      type: 'headtextimg',
    },
    {
      text: "Instead, they want you to get the point across as quickly and clearly as possible so you can get to the most important parts to go through your plans and decide if your opportunity is worth considering. start doing).",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%2C%20analytics%2C%20sucess%2C%20startup%2C%20Technology%20_%20account%2C%20setting%2C%20options%2C%20preferences.png?alt=media&token=d017d4cc-0626-488c-8b25-2a478282e65b',
      type: 'textimg',
    },
    {
      text: "You should be able to articulate all the core values ​​investors are looking for, up to 15-20 pages (not including appendices detailing financial information).\n\nIf you're writing more than that, you're probably overly explanatory, repeating information, or including irrelevant details (eg you don't have to spend 10 pages on how to set up a website)",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%2C%20analytics%2C%20sucess%2C%20startup%2C%20Technology%20_%20account%2C%20setting%2C%20options%2C%20preferences.png?alt=media&token=d017d4cc-0626-488c-8b25-2a478282e65b',
      type: 'textimg',
    },
    {
      text: "The bottom line is that you should always be on the lookout for methods to \"Trim the fat.\"",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%2C%20analytics%2C%20sucess%2C%20startup%2C%20Technology%20_%20account%2C%20setting%2C%20options%2C%20preferences.png?alt=media&token=d017d4cc-0626-488c-8b25-2a478282e65b',
      type: 'textimg',
    },
    {
      heading: '2. Recognize Your Target Market',
      text: "If you pack your business plan with buzzwords, industry-specific jargon or acronyms, and long, difficult phrases, it may make sense to a few people familiar with your specialty and those with superhuman attention spans (not many), but it will alienate the great majority of non-expert readers.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%2C%20analytics%2C%20sucess%2C%20startup%2C%20Technology%20_%20account%2C%20setting%2C%20options%2C%20preferences.png?alt=media&token=d017d4cc-0626-488c-8b25-2a478282e65b',
      type: 'headtextimg',
    },
    {
      text: "Use basic, straightforward language that everyone can understand — from the most savvy investor to your Great Aunt Bertha who still uses a landline — and you'll be fine.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%2C%20analytics%2C%20sucess%2C%20startup%2C%20Technology%20_%20account%2C%20setting%2C%20options%2C%20preferences.png?alt=media&token=d017d4cc-0626-488c-8b25-2a478282e65b',
      type: 'textimg',
    },
    {
      question: 'Which of the following is sweat equity?',
      options: [
        'Operating Model',
        'Business Canvas Model',
        'product',
        'market',
      ],
      ans: 1,
      type: 'quiz',
    },
    {
      heading: 'How to Approach Writing a Business Plan?',
      text: "Here are some useful tips to help you get organized and give you the confidence to tackle this head on.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: 'A. Nail The Research First',
      text: "Going into this knowing everything there possibly is to know about the market you will be competing in, who your audience is, and how you will make money will always be the first step in the business planning process.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      text: "Conducting the necessary fact gathering will also help you prove or disprove any assumptions you have about your market fit — either validating what you initially thought, or telling you it’s time to go back to the drawing board.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'textimg',
    },
    {
      heading: 'B. Create a Business Plan Outline',
      text: "We talked before about the key components that you’ll want to include in your business plan. Instead of jumping in willy-nilly, draft a very basic outline of each of the sections that you will touch on in your business plan. Not only will this make it significantly easier to stay laser focused on only detailing the relevant information you need for each specific section, but it will help the writing process feel much more manageable by breaking it up into bite-sized pieces.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: 'C. Organize Your Goals and Objectives',
      text: "Start dividing up all of the information that you need to include in your business plan by section. The best way to do this is by thinking about each section as if it were comprised of a series of questions that your readers will want answered.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      text: "For example, in the Customer Acquisition section, some of the key questions you want to address are:\n - How will you reach your target customers?\n - What marketing strategies will you use?\n - What will it cost to acquire customers?",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'textimg',
    },
    {
      question: 'What are the things you should do before you start writing your business Plan?',
      options: [
        'Researching the market, audience, and how you are going to make money',
        'Create a Business Plan Outline',
        'dividing up all of the information that you need to include in your business plan by section',
        'all of these',
      ],
      ans: 3,
      type: 'quiz',
    },
    {
      text: "Once you’ve laid this out for each section, you now have a good jumping-off point to go in and start shedding light on each of these key questions.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'textimg',
    },
    {
      heading: 'What Is The Best Way To Format Your Business Plan?',
      text: "While there is no one-size-fits-all approach to formatting your plan, the goal is to make it look professional.\n\nIf your company plan has a lot of different fonts and margins, it's time to rewrite it",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      text: "Here are some simple formatting recommendations to get you started.:",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'textimg',
    },
    {
      heading: 'Margins',
      text: "If the margins are too thin, the page will appear cluttered and difficult to read. Sticking to conventional one-inch margins all around is a decent rule of thumb.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: 'Headings',
      text: "Your company plan is divided into numerous major components, much like a book's chapters. You should use a header to indicate the start of a section (\"Traction,\" for example) so that your reader understands what to expect from the content that follows.This also aids in the organisation of your content by breaking it up.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: 'Subheadings',
      text: "Subheadings are tiny versions of headings that are used to split up text within each section and keep readers moving down the page by capturing their attention. In fact, we're doing just that right now in this section with subheaders!",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: 'Types of Font',
      text: "Limit yourself to two typefaces (for example, one for headers and another for body copy and subheadings) that you can find in a typical text editor like Microsoft Word or Google Docs. Choose fonts that are simple to read and have both capital and lowercase letters.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: 'Font Dimensions',
      text: "To ensure readability, keep your body copy between 11 and 12 point font size (some fonts are more squint-inducing than others).\n\nSimply increase the font size and bold your subheadings to offset your headings from your body material.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: 'Visuals',
      text: "It's sometimes preferable to show rather than tell. Assume that your readers will scan your plan rather than reading it word for word, and use colour graphics, tables, and charts (particularly with financial forecasts), as well as product photographs, if relevant, to capture their attention. This will also assist your reader in better understanding what your company is all about.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: 'Continue to refine',
      text: "A solid business plan is constantly changing, and no one detail is ever fixed in stone. This means that the first version of your strategy is unlikely to be the last (and should not be).",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      text: "It's vital to check your business plan from time to time as your business grows and your thoughts about it change, to ensure that it represents those changes and that everything is as accurate and up-to-date as possible.\n\nThis is especially true when conducting market research and discovering information that contradicts your initial ideas.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'textimg',
    },
    {
      text: "You'll also need a reliable business critic who can review your work and provide helpful criticism on how it reads stylistically. While different investors have different preferences, the important thing is to be consistent with your audience and business.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'textimg',
    },
    {
      question: 'What is the recommended font size for business plan?',
      options: [
        '16-18',
        '15-16',
        '20-21',
        '11-12',
      ],
      ans: 3,
      type: 'quiz',
    },
    {
      heading: 'A Section-by-Section Guide to Writing Your Business Plan:',
      text: "",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: 'Executive Summary',
      text: "The Executive Summary will be the first portion of actual content about your firm after your Title Page — which includes your company name, tagline (if relevant), and contact information — and your Table of Contents.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      text: "Your Executive Summary's major purpose is to give your readers a high-level overview of your entire business plan by summarizing the most significant components in a few brief phrases. \n\nConsider your Executive Summary to be a \"teaser\" for the content that will follow — information that will be explained in greater depth throughout your strategy.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'textimg',
    },
    {
      heading: '2. Company Synopsis',
      text: "In your Company Synopsis section, you should answer two crucial questions for your readers: What unpleasant PROBLEM are you fixing for your customers? And, more importantly, what is your brilliant SOLUTION to the problem?",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: '3. The Market Overview',
      text: "Your Market Overview provides context for the industry in which your product or service will compete. Statistics on the size, growth rate, trends, and overall outlook of the industry will be included. This aspect of your business plan may be described in one word: research.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      text: "The idea is to assemble as much raw data as possible in order to persuade your readers that: \n\nThis is a market worth getting excited about. You have a strong possibility of snagging a sizable chunk of this market.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'textimg',
    },
    {
      question: 'What is the purpose of executive summary?',
      options: [
        'to give your readers a high-level in-depth information of some parts of your business plan',
        'to give your readers a low-level overview of your entire business plan',
        'to give your readers a high-level overview of your entire business plan ',
        'to give your readers a high-level overview of some parts of your business plan',
      ],
      ans: 0,
      type: 'quiz',
    },
    {
      heading: '4. Product (How it Works)',
      text: "Whereas your Company Synopsis is supposed to explain why the company exists by illustrating the problem you're trying to solve and then backing it up with a compelling solution, your Product or How it Works section allows you to dig into the fine gritty of how it truly delivers that value.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: '5. Revenue Model',
      text: "Simply said, your Revenue Model provides a framework for your readers to understand how you intend to make money. It determines the revenue sources you're using, as well as how and why you're pricing your product or service.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: '6. Operating Model',
      text: "Simply said, your Operating Model describes how your business operates. It's a detailed explanation of the processes, technologies, and physical requirements (assets) that enable you to deliver the value your product or service delivers to your customers.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: '7. Analyze your competition',
      text: "Your Competitive Analysis, like the Market Overview section, informs your readers that you've done your homework and have a ridiculously high degree of understanding about your existing competitors as well as any possible competitors down the road.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      text: "When composing your Competitive Analysis, your summary should include who your nearest competitors are, what their main strengths and shortcomings are. At least three competitors — direct, indirect, or a mix of the two — should be identified.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'textimg',
    },
    {
      heading: '8. Customer Definition',
      text: "Your Customer Definition section allows you to note which customer segment(s) you're targeting, what characteristics and habits each segment embodies, how each segment benefits from your product or service in a unique way, and how all of this ties together to create the ideal portrait of an actual paying customer.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: '9. Customer Acquisition',
      text: "Your Customer Acquisition section will explain your readers which techniques and tactics you plan to use to actually approach those people and turn them into paying customers now that you've defined who your customers are for them.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: '10.Traction',
      text: "This is a large one. Traction informs investors one key thing: your company is moving forward. It's proof that you're making progress and accomplishing goals. That is exactly what is happening.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      text: "What is the significance of this?\n\nBecause if you can show investors that your firm has legs before they put any money into it, it will make them think about all the fantastic things you'll be able to accomplish once they do.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'textimg',
    },
    {
      question: 'What tells readers how you intend to make money?',
      options: [
        'Revenue model ',
        'Product',
        'Traction',
        'Operating model',
      ],
      ans: 0,
      type: 'quiz',
    },
    {
      heading: '11. The Management Team',
      text: "What your Management Team section isn't: it's not a comprehensive list of every role your team members have held during their careers. Instead, your Management Team section should explain to investors how each member of your team's experience and skill contributes to the company's and industry's success.\n\nIn other words, what relevant and applicable experience do they bring to the table?",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: '12. Funding',
      text: "This is when you come out and ask your investors straight up how much money you need to drive your business ahead, what precise milestones their investment will enable you to hit, how you'll deploy the capital you secure, and what the investor will get in return for their contribution. You can also provide details on your exit strategy (IPO, acquisition, merger, etc.)",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      heading: '13. Financials',
      text: "Oh, the spreadsheets, numbers, and charts! Financials are, without a doubt, everyone's \"favourite\" element of a business plan.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      text: "Your Financials section will be last, and it will include all of the projected numbers that investors will use to determine whether or not this is a good investment. This will comprise your sales projection, spending budget, and break-even analysis, among other things. A large portion of this will be based on assumptions or estimations.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'textimg',
    },
    {
      text: "Breaking down your data into components and looking at each one individually is the key to keeping your estimations as realistic as possible.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'textimg',
    },
    {
      heading: 'Finally!',
      text: "You've made the decision to write your business plan, and now you've got some tips to help you along the path. Your well-crafted business plan will work as your Holy Grail in helping you take your firm to the next level, whether you're applying for a loan or looking for investors.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'headtextimg',
    },
    {
      text: "This is a huge task. We've been in that situation previously. Writing a business plan is only the first step in the startup process. You have a long road ahead of you, filled with investor outreach, genuine funding, and business growth.",
      image: 'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%20Plan.png?alt=media&token=9fb2c48f-6d67-4ce6-b9c0-003485b70694',
      type: 'textimg',
    },
    ]
   },
   {
    name:"model4",
    slides:[
    {
      heading: 'End Questions',
      image:'https://firebasestorage.googleapis.com/v0/b/reverr-25fb3.appspot.com/o/courses%2FBusinessPlanning%2FBusiness%2C%20analytics%2C%20sucess%2C%20startup%2C%20Technology%20_%20account%2C%20setting%2C%20options%2C%20preferences.png?alt=media&token=d017d4cc-0626-488c-8b25-2a478282e65b',
      type: 'intro',
    },
    {
      question: 'Which among the following are why questions?',
      options: [
        'Why this?',
        'Why now?',
        'Why you?',
        'all of these',
      ],
      ans: 3,
      type: 'quiz',
    },
    {
      question: 'Which among the following is/are one of the reasons you need business plan?',
      options: [
        'To plan your objectives',
        'To analyze your competitors',
        'To obtain business plan',
        'Both A & C',
      ],
      ans: 2,
      type: 'quiz',
    },
    {
      question: 'Which among the following is/are one of the reasons you need business plan?',
      options: [
        'To plan your objectives',
        'To analyze your competitors',
        'To obtain business plan',
        'Both A & C',
      ],
      ans: 2,
      type: 'quiz',
    },
    {
      question: 'What is the purpose of an internal business plan?',
      options: [
        'to convince investors to financially support your business',
        'to create early conversations with a potential investor.',
        'designed to serve as a management tool to help business owners plan and meet goals',
        'to arouse interest and set up a forum for in-depth discussions about your business after your initial contact.',
      ],
      ans: 2,
      type: 'quiz',
    },
    {
      question: 'Which of the following is a part of key components?',
      options: [
        'Management Team',
        'traction',
        'Market size',
        'all of these',
      ],
      ans: 3,
      type: 'quiz',
    },
    {
      question: 'What does financial section of your key components include?',
      options: [
        'asking your investors straight up how much money you need to drive your business ahead, what precise milestones their investment will enable you to hit',
        'it includes all of the projected numbers that investors will use to determine whether or not this is a good investment.',
        'informs your readers that you\'ve done your homework and have a ridiculously high degree of understanding about your existing competitors',
        'provides a framework for your readers to understand how you intend to make money',
      ],
      ans: 2,
      type: 'quiz',
    },
    {
      question: 'Which of the following best describes the key component “Operating Model”?',
      options: [
        'It describes how your company will make money',
        'It is all about smart ways to manage costs and work efficiently to earn it',
        'It shows revenue projection for the next 5 years',
        'Both A & C',
      ],
      ans: 2,
      type: 'quiz',
    },
    ]
   },
  ],
};

