export const mentorCategory = [
  'Agriculture & Allied Industries',
  'Design',
  'Edtech',
  'Education',
  'Enterprise software',
  'Engineering & Capital Goods',
  'Finance',
  'Fintech',
  'Healthcare & lifesciences',
  'Human resources',
  'Insurance',
  'IT Services',
  'Manufacturing',
  'Marketing',
  'Media and entertainment',
  'Other speciality retailers',
  'Social impact',
  'Travel and tourism',
  'Waste management',
];
