import { StyleSheet, Dimensions } from 'react-native';
import { AppColors } from '../../utils';
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000C12',
  },
  screen: {
    flex: 1,
    paddingHorizontal: '5%',
    justifyContent: 'center',
    backgroundColor: AppColors.primarycolor,
  },
  card: {
    alignSelf: 'center',
    position: 'absolute',
    bottom: 125,
    width: Dimensions.get('window').width / 1.12,
    height: Dimensions.get('window').height / 1.49,
    // flex:1,
    marginHorizontal: 35,
    marginVertical: 20,
    borderTopRightRadius: 50,
    borderTopLeftRadius: 50,
    borderBottomLeftRadius: 45,
    borderBottomRightRadius: 45,

    padding: 2,
    backgroundColor: 'black',
    borderWidth: 2,
    borderColor: 'dodgerblue',
  },
  image: {
    width: Dimensions.get('window').width / 1.17,
    height: Dimensions.get('window').height / 2.5,
    borderTopRightRadius: 50,
    borderTopLeftRadius: 50,
    opacity: 0.9,
    display: 'flex',
    justifyContent: 'flex-end',
    resizeMode: 'cover',
  },

  heading: {
    color: '#0077B7',
    fontWeight: 'bold',
    maxWidth: Dimensions.get('window').width / 1.2,
    fontSize: 22,
  },
  button: {
    backgroundColor: '#0077B7',
    width: 300,
    height: 60,
    borderRadius: 25,
    marginTop: 35,
    marginLeft: 50,
    alignItems: 'center',
    alignContent: 'center',
    display: 'flex',
    flexDirection: 'row',
    paddingHorizontal: 30,
  },
  likeContainer: {
    left: 45,
    top: Dimensions.get('window').height / 14,
    position: 'absolute',
    transform: [{ rotate: '-30deg' }],
    zIndex: 3,
  },
  unlikeContainer: {
    right: 45,
    top: Dimensions.get('window').height / 14,
    position: 'absolute',
    transform: [{ rotate: '30deg' }],
    zIndex: 3,
  },
  loader: {
    width: '100%',
    height: '80%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modelViewOne: {
    backgroundColor: '#fff',
    borderRadius: 15,
    marginHorizontal: 20,
    alignSelf: 'center',
    flex: 1,
    marginVertical: 20,
    borderColor: '#0C0C0D',
    borderWidth: 1,
  },
  modelViewTwo: {
    flexDirection: 'row',
    marginHorizontal: 15,
    marginVertical: 10,
    alignSelf: 'center',
  },
  modelText: {
    color: '#000',
    fontSize: 16,
    marginEnd: 20,
    fontWeight: 'bold',
    flex: 1,
    textAlign: 'center',
  },
  ModelBack: {
    flex: 1,
    backgroundColor: 'rgba(52, 52, 52, 0.8)',
  },
  viewLike: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  viewLike1: {

    borderWidth: 1,
    alignItems: "center",


    height: 42,
    flexDirection: "row",
    left: 40,
    justifyContent: 'center',

  },
  likeText: {
    backgroundColor: '#000C12',
    color: 'white',
    marginLeft: 7,
    textAlign: 'center',
    alignSelf: 'center',
    fontWeight: '700',
  },
  MainCard: {
    alignSelf: 'center',
    width: Dimensions.get('window').width / 1.12,
    height: Dimensions.get('window').height / 1.49,
    marginVertical: 20,
    borderTopRightRadius: 50,
    borderTopLeftRadius: 50,
    marginHorizontal: 20,
    borderBottomLeftRadius: 45,
    borderBottomRightRadius: 45,
    padding: 2,
    paddingHorizontal: 20,
    backgroundColor: '#0C0C0D',
    borderWidth: 2,
    borderColor: 'dodgerblue',
  },
  coverImage: {
    width: 130,
    alignSelf: 'center',
    height: 130,
    borderRadius: 100,
    borderColor: "#06FF79",
    borderWidth: 2,
    resizeMode: 'cover',
  },
  viewText: {
    marginHorizontal: 10,
    marginTop: 5,
    alignItems: 'center',
  },
  txtName: {
    color: 'white',
    fontSize: 22,
    fontFamily: 'poppins',
    fontWeight: 'bold',
  },
  ceo: {
    color: '#8CB2F4',
    fontSize: 14,
    fontWeight: '400',
  },
  Delhi: {
    color: '#999999',
    fontSize: 12,
    fontWeight: '400',
  },
  about: {
    color: '#78D2FF',
    fontFamily: 'Poppins',
    fontSize: 18,
    marginTop: 6,
    fontWeight: '700',
    marginLeft: 15,
  },
  detial: {
    color: '#EFEFEF',
    fontFamily: 'Poppins',
    fontSize: 14,
    marginVertical: 10,
    fontWeight: '400',

    alignSelf: 'center',
    marginLeft: 5,
  },
  likebar: {
    alignItems: 'center',
    alignSelf: 'center',
    flexDirection: 'row',
    marginTop: 10,
    backgroundColor: '#121416',
    flex: 1,
    height: 55,
    borderRadius: 10,
  },
  nope: {
    height: 32,
    width: 32,
  },
  nopes: {
    height: 32,
    width: 32,
    marginStart: 10,
  },
  textwhite: {
    color: "#fff"
  },
  textwhites: {
    color: "#fff",
    marginStart: 5
  },
  superLike: { flex: 1, marginRight: 15 },
  nopeText: { marginStart: 10, flex: 1 },
  entypo: { alignSelf: 'center', marginTop: 20 },
  noData: {
    color: '#EFEFEF',
    fontFamily: 'Poppins',
    fontSize: 14,
    fontWeight: '400',
    marginLeft: 15,
  },
  vibeText: {
    color: '#78D2FF',
    fontFamily: 'Poppins',
    fontSize: 18,
    marginTop: 6,
    fontWeight: '700',
    marginLeft: 15,
  },
  viewVibe: {
    marginTop: 8,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    flexWrap: 'wrap',
  },
  circle: {
    boxShadow:
      '4px -5px 5px 0px #00000040 inset',

    alignItems: 'center',
    justifyContent: 'center',

    borderRadius: 100 / 2,
    borderWidth: 3,
    borderColor: 'white',
    backgroundColor: '#0077B7',
    height: 80,
    width: 80,
  },
  hareFor: { textAlign: "center", color: "#fff" },
  dataDatabase: {
    color: 'white',
    marginLeft: 15,
    fontFamily: 'Poppins',
    fontSize: 13,
    fontWeight: '500',
  },

});
